name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-with-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --features=image
    - name: Run tests
      run: cargo test --verbose --features=image
      
  build-with-mediainfo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install MediaInfo
      run: |
        sudo apt-get update
        sudo apt-get install -y mediainfo
    - name: Build
      run: cargo build --verbose --features=mediainfo
    - name: Run tests
      run: cargo test --verbose --features=mediainfo

  build-with-mediainfo-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: Cyberboss/install-winget@v1
    - name: Install MediaInfo
      run: |
        $location = "$((Get-Item .).FullName)\__mediainfo"
        winget install MediaArea.MediaInfo --accept-source-agreements --accept-package-agreements -l $location
        $env:Path = "$env:Path;$location;"
    - name: Build
      run: cargo build --verbose --features=mediainfo
    - name: Run tests
      run: cargo test --verbose --features=mediainfo

  cargo-fmt:
    name: cargo fmt -- --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check

  cargo-doc:
    name: RUSTDOCFLAGS='--deny warnings' cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: RUSTDOCFLAGS='--deny warnings' cargo doc --locked --no-deps --document-private-items
